### ISSUE TITLE
Plugin does not work, Sublime Text 3, Build 3083, Windows 7

### ISSUE THREAD

**Issue by grefel** [vamitul/RunInIndesign#1]
I've installed the plugin via package manager in Sublime Text 3 Build 3083 on Windows 7. Unfortunately nothing happens. I testet a simple alert("hello"); script with and without #target. The plugin opens another Window on the bottom, with text: Running test.jsx with Indesign CS6 but the script is not executed in InDesing. 

I tested the runJs.vbs script via commandline with success. 

Is there any log I can search for. Any Ideas?

**Comment by vamitul** [comment]
Anything in Sublime's console (press ctr+~ to open it)?
The plugin uses ESTK sockets facilitate communication between indesign and Sublime, so it might be an issue with windows firewall disallowing such communication.

**Comment by grefel** [comment]
Firewall is wide open :-) 
Console says: 

> File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
>    return self.run(edit, **args)
>  File "runInIndesign in C:\Users\hp\AppData\Roaming\Sublime Text 3\Installed Packages\Run In InDesign.sublime-package", line 20, in run
>  File "runInIndesign in C:\Users\hp\AppData\Roaming\Sublime Text 3\Installed Packages\Run In InDesign.sublime-package", line 46, in runC
>  File "runInIndesign in C:\Users\hp\AppData\Roaming\Sublime Text 3\Installed Packages\Run In InDesign.sublime-package", line 238, in scanAndFixTargetEngine
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\hp\AppData\Roaming\Sublime Text 3\Installed Packages\Run In InDesign.sublime-package\utils\jsRunner.jsx'

jsRunner.jsx is in place...

**Comment by vamitul** [comment]
that's unfortunate!
Could you unzipping the Run In InDesign.sublime-package in a folder in the "Packages" folder, and then removing the original package?
Looks like the file is inaccessible inside a package

**Comment by vamitul** [comment]
Hi Gregor,
I have updated the package, it should now work, but just to be on the safe side, please remove it first and reinstall it.

**Comment by grefel** [comment]
Hey Vamitul, 

sorry for not coming back earlier, but I need to take care of my daugther. 
You fixed it already and it works great now.

Thanks for your work!
