### ISSUE TITLE
Will you join forces with us in the Extendscript Org 

### ISSUE THREAD

**Issue by ff6347** [vamitul/RunInIndesign#4]
Hi @vamitul great package you have here. What about joining forces on the Extendscript Org here on GitHub? We are about 30 members now trying to join forces on different topics like editor packages, documentation and what not. You should have an invite here https://github.com/ExtendScript and/or per mail.

**Comment by vamitul** [comment]
I did

**Comment by ff6347** [comment]
Awesome. Welcome. Take a look into the [AMA](https://github.com/ExtendScript/AMA/issues) repo. This is where discussion is currently happening. You are very welcome to improve the [wiki](https://github.com/ExtendScript/wiki/wiki) with us or just ist back, relax and watch the chaos happening. ;-)
