### ISSUE TITLE
Does not work out of the box with InDesign CC2015

### ISSUE THREAD

**Issue by trych** [vamitul/RunInIndesign#5]
Hi, I'm trying to install this for an entire classroom which has ID CC 2015 installed.

By default the package seems to look for ID CC 2014. It will then ask you: «Where is InDesign 2014» and you can simply link it to the ID CC 2015 app, which seems to work just fine and is simple enough.

So it's not a huge issue, but if it could recognize ID CC 2015 from the start that would be even nicer. :)

**Comment by trych** [comment]
Also, I realized on my local copy (that I installed just yesterday via the PackageManager) [this file](https://github.com/vamitul/RunInIndesign/blob/master/RunInIndesign.sublime-settings) does not contain anything about InDesign CC 2015. Is the Package that gets pulled into Sublime by the package manager maybe behind the version here on GitHub?

**Comment by ff6347** [comment]
Same for me.

**Comment by vamitul** [comment]
Should be fixed for the moment.
